language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jordan-castillo-github"
    token:
      secure: "55e1438d4911c88b0f165c899dbfc8d4307d8189"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      
